"""
auto_grow_text_edit.py
======================
Drop-in composite widget for mainUI.py's AutoGrowTextEdit instances.

LAYOUT (everything lives INSIDE the rounded QFrame):
─────────────────────────────────────────────────────────────────
  QFrame#iFrame
    ├── _strip        chip row (hidden by default)
    │     ├── _LoadingChip  (gif + "Uploading…" + filename)
    │     └── _AttachChip   (ext badge/thumb + filename + ✕)
    ├── _edit         _InnerEdit (grows between TEXT_MIN … TEXT_MAX)
    └── _btn_row      bottom toolbar row
          ├── add_btn      QPushButton  (public – wire to open_document)
          ├── [stretch]
          └── search_btn   QPushButton  (public – wire to send/stop)
─────────────────────────────────────────────────────────────────

Public attributes
-----------------
add_btn    : QPushButton  – the + attachment button (bottom-left)
search_btn : QPushButton  – the 🔍/⏹ button        (bottom-right)

Signals
-------
height_changed(int)
    Emitted on every height change.
    • main.py connects on text_prompt_2 → resizes frame_2 (upward growth).

pyuic5 compatibility stubs
--------------------------
mainUI.py (generated by pyuic5) calls several QTextEdit / QFrame methods on
this object.  They are silently ignored or proxied so that even an
un-patched pyuic5 output works without manual editing.
"""

from PyQt5.QtWidgets import (
    QWidget, QTextEdit, QVBoxLayout, QHBoxLayout,
    QLabel, QPushButton, QFrame, QSizePolicy
)
from PyQt5.QtCore import Qt, pyqtSignal, QEvent, QSize
from PyQt5.QtGui import QFont, QPixmap, QPainter, QPainterPath, QMovie, QIcon

import os


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _rounded_pixmap(pixmap: QPixmap, radius: int = 8) -> QPixmap:
    result = QPixmap(pixmap.size())
    result.fill(Qt.transparent)
    p = QPainter(result)
    p.setRenderHint(QPainter.Antialiasing)
    path = QPainterPath()
    path.addRoundedRect(0, 0, pixmap.width(), pixmap.height(), radius, radius)
    p.setClipPath(path)
    p.drawPixmap(0, 0, pixmap)
    p.end()
    return result


# ─────────────────────────────────────────────────────────────────────────────
# Loading chip  (gif spinner + "Uploading…" + filename)
# Appears in the strip while the file is being read — add_btn stays visible.
# ─────────────────────────────────────────────────────────────────────────────
class _LoadingChip(QFrame):
    CHIP_H = 56

    def __init__(self, gif_path: str, filename: str, parent=None):
        super().__init__(parent)
        self.setFixedHeight(self.CHIP_H)
        self.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.setStyleSheet("""
            QFrame {
                background-color: rgb(46, 52, 66);
                border-radius: 10px;
                border: 1px solid rgba(85,170,255,80);
            }
        """)

        row = QHBoxLayout(self)
        row.setContentsMargins(10, 6, 14, 6)
        row.setSpacing(10)

        # Spinning gif
        self._gif_lbl = QLabel()
        self._gif_lbl.setFixedSize(28, 28)
        self._gif_lbl.setAlignment(Qt.AlignCenter)
        self._movie = QMovie(gif_path)
        self._movie.setScaledSize(QSize(24, 24))
        self._gif_lbl.setMovie(self._movie)
        self._movie.start()
        row.addWidget(self._gif_lbl)

        # Text column
        col = QVBoxLayout()
        col.setSpacing(1)
        col.setContentsMargins(0, 0, 0, 0)

        up_lbl = QLabel("Uploading…")
        up_lbl.setStyleSheet("""
            color: rgb(85,170,255);
            font-family: 'Roboto'; font-size: 9pt;
            background: transparent; border: none;
        """)
        col.addWidget(up_lbl)

        fn_lbl = QLabel()
        fn_lbl.setText(QLabel().fontMetrics().elidedText(filename, Qt.ElideMiddle, 150))
        fn_lbl.setToolTip(filename)
        fn_lbl.setStyleSheet("""
            color: rgba(255,255,255,110);
            font-family: 'Roboto'; font-size: 8pt;
            background: transparent; border: none;
        """)
        col.addWidget(fn_lbl)
        row.addLayout(col)
        row.addStretch()
        self.adjustSize()

    def stop(self):
        self._movie.stop()


# ─────────────────────────────────────────────────────────────────────────────
# Attachment chip  (ext badge / thumbnail  +  filename + type  +  ✕)
# ─────────────────────────────────────────────────────────────────────────────
class _AttachChip(QFrame):
    remove_requested = pyqtSignal()
    CHIP_H = 56

    def __init__(self, filename: str, pixmap: QPixmap = None, parent=None):
        super().__init__(parent)
        self.setFixedHeight(self.CHIP_H)
        self.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.setStyleSheet("""
            QFrame {
                background-color: rgb(55, 60, 76);
                border-radius: 10px;
                border: none;
            }
        """)

        row = QHBoxLayout(self)
        row.setContentsMargins(8, 5, 10, 5)
        row.setSpacing(8)

        # Thumbnail or ext badge
        thumb = QLabel()
        thumb.setAlignment(Qt.AlignCenter)
        if pixmap and not pixmap.isNull():
            scaled = pixmap.scaled(56, 42, Qt.KeepAspectRatio, Qt.SmoothTransformation)
            thumb.setPixmap(_rounded_pixmap(scaled, 6))
            thumb.setFixedSize(56, 42)
        else:
            ext = os.path.splitext(filename)[1].upper().lstrip('.') or "FILE"
            thumb.setText(ext)
            thumb.setFixedSize(40, 34)
            thumb.setStyleSheet("""
                background-color: rgb(72, 86, 114);
                border-radius: 7px;
                color: rgba(255,255,255,230);
                font-size: 9px;
                font-family: 'Roboto'; font-weight: bold;
            """)
        row.addWidget(thumb)

        # Name + type column
        col = QVBoxLayout()
        col.setSpacing(1)
        col.setContentsMargins(0, 0, 0, 0)

        name_lbl = QLabel()
        fm = name_lbl.fontMetrics()
        name_lbl.setText(fm.elidedText(filename, Qt.ElideMiddle, 160))
        name_lbl.setToolTip(filename)
        name_lbl.setStyleSheet("""
            color: rgba(255,255,255,215);
            font-family: 'Roboto'; font-size: 9pt;
            background: transparent; border: none;
        """)
        col.addWidget(name_lbl)

        ext_str = os.path.splitext(filename)[1].upper().lstrip('.')
        type_lbl = QLabel(f"{ext_str} file" if ext_str else "file")
        type_lbl.setStyleSheet("""
            color: rgba(255,255,255,95);
            font-family: 'Roboto'; font-size: 8pt;
            background: transparent; border: none;
        """)
        col.addWidget(type_lbl)
        row.addLayout(col)
        row.addStretch()

        # ✕ button
        x_btn = QPushButton("✕")
        x_btn.setFixedSize(20, 20)
        x_btn.setCursor(Qt.PointingHandCursor)
        x_btn.setStyleSheet("""
            QPushButton {
                background: rgba(255,255,255,18);
                color: rgba(255,255,255,130);
                border-radius: 10px;
                font-size: 9px; border: none;
            }
            QPushButton:hover {
                background: rgb(232, 0, 116); color: white;
            }
        """)
        x_btn.clicked.connect(self.remove_requested)
        row.addWidget(x_btn, 0, Qt.AlignVCenter)
        self.adjustSize()


# ─────────────────────────────────────────────────────────────────────────────
# Inner bare QTextEdit  (no height logic — parent handles all of that)
# ─────────────────────────────────────────────────────────────────────────────
class _InnerEdit(QTextEdit):
    def __init__(self, parent=None):
        super().__init__(parent)
        self._default_font = QFont("Roboto", 10)
        self.setFont(self._default_font)
        self.setLineWrapMode(QTextEdit.WidgetWidth)
        self.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        self.setHorizontalScrollBarPolicy(Qt.ScrollBarAlwaysOff)
        self.setFrameShape(QTextEdit.NoFrame)
        self.document().setDocumentMargin(2)
        self.setStyleSheet("""
            QTextEdit {
                background: transparent;
                color: rgba(255,255,255,210);
                border: none; padding: 0px;
            }
        """)

    def keyPressEvent(self, event):
        if event.key() in (Qt.Key_Return, Qt.Key_Enter):
            if event.modifiers() & Qt.ShiftModifier:
                super().keyPressEvent(event)   # Shift+Enter → newline
            else:
                event.ignore()                 # Enter → main window handles send
            return
        super().keyPressEvent(event)


# ─────────────────────────────────────────────────────────────────────────────
# PUBLIC  AutoGrowTextEdit
# ─────────────────────────────────────────────────────────────────────────────
class AutoGrowTextEdit(QWidget):
    height_changed = pyqtSignal(int)

    # ── Sizes ──────────────────────────────────────────────────────────────────
    _TEXT_MIN  = 36      # minimum _InnerEdit height
    _TEXT_MAX  = 140     # max _InnerEdit height before scrolling
    _CHIP_H    = _AttachChip.CHIP_H      # 56
    _STRIP_GAP = 6       # gap between chip strip and text edit
    _BTN_H     = 40      # bottom toolbar row height
    _BTN_ROW_GAP = 6     # gap between text edit and button row
    _V_PAD     = 8       # top and bottom padding inside the frame (each)
    _RADIUS    = 22

    GIF_PATH = "Reqs/loading.gif"

    # Stylesheet templates
    _SS_NORMAL = (
        "QFrame#iFrame{{"
        "border:2px solid rgb(41,44,53);"
        "border-radius:{r}px;"
        "background-color:rgb(41,44,53);}}"
        "QFrame#iFrame:hover{{border:2px solid rgb(220,0,220);}}"
    )
    _SS_FOCUS = (
        "QFrame#iFrame{{"
        "border:2px solid rgb(85,170,255);"
        "border-radius:{r}px;"
        "background-color:rgb(41,44,53);}}"
    )

    def __init__(self, parent=None):
        super().__init__(parent)
        self.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)

        self._attachment   = None
        self._chip         = None    # _AttachChip | None
        self._loading_chip = None   # _LoadingChip | None

        # ── Outer rounded frame ───────────────────────────────────────────────
        self._frame = QFrame(self)
        self._frame.setObjectName("iFrame")
        self._frame.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self._frame.setStyleSheet(self._SS_NORMAL.format(r=self._RADIUS))

        self._flayout = QVBoxLayout(self._frame)
        self._flayout.setContentsMargins(12, self._V_PAD, 12, self._V_PAD)
        self._flayout.setSpacing(0)

        # ── 1. Chip strip (hidden by default) ─────────────────────────────────
        self._strip = QWidget()
        self._strip.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        self._strip.setFixedHeight(self._CHIP_H)
        self._strip_layout = QHBoxLayout(self._strip)
        self._strip_layout.setContentsMargins(0, 0, 0, 0)
        self._strip_layout.setSpacing(8)
        self._strip_layout.addStretch()
        self._strip.hide()
        self._flayout.addWidget(self._strip)

        self._flayout.addSpacing(self._STRIP_GAP)

        # ── 2. Inner text edit ────────────────────────────────────────────────
        self._edit = _InnerEdit(self._frame)
        self._edit.setFixedHeight(self._TEXT_MIN)
        self._edit.setPlaceholderText("Ask Anything")
        self._flayout.addWidget(self._edit)

        self._flayout.addSpacing(self._BTN_ROW_GAP)

        # ── 3. Bottom toolbar row: [add_btn] ─── stretch ─── [search_btn] ─────
        btn_row = QHBoxLayout()
        btn_row.setContentsMargins(0, 0, 0, 0)
        btn_row.setSpacing(0)

        # + button (public)
        self.add_btn = QPushButton()
        self.add_btn.setFixedSize(self._BTN_H, self._BTN_H)
        self.add_btn.setCursor(Qt.PointingHandCursor)
        self.add_btn.setToolTip("Attach a document")
        _add_icon = QIcon("Reqs/add_icon.png")
        if not _add_icon.isNull():
            self.add_btn.setIcon(_add_icon)
            self.add_btn.setIconSize(QSize(22, 22))
        else:
            self.add_btn.setText("+")
            self.add_btn.setFont(QFont("Roboto", 14))
        self.add_btn.setStyleSheet("""
            QPushButton {
                background: none; border: none;
                color: rgba(255,255,255,180);
                border-radius: 20px;
            }
            QPushButton:hover { background-color: rgb(55,59,72); }
        """)
        btn_row.addWidget(self.add_btn)
        btn_row.addStretch()

        # 🔍 / ⏹ search-or-stop button (public)
        self.search_btn = QPushButton()
        self.search_btn.setFixedSize(self._BTN_H, self._BTN_H)
        self.search_btn.setCursor(Qt.PointingHandCursor)
        _search_icon = QIcon("Reqs/search.png")
        if not _search_icon.isNull():
            self.search_btn.setIcon(_search_icon)
            self.search_btn.setIconSize(QSize(24, 24))
        else:
            self.search_btn.setText("🔍")
        self.search_btn.setStyleSheet("""
            QPushButton {
                background-color: rgb(41,44,53);
                border: none; border-radius: 20px;
                color: rgba(255,255,255,180);
            }
            QPushButton:hover { background-color: rgb(55,59,72); }
        """)
        btn_row.addWidget(self.search_btn)

        self._flayout.addLayout(btn_row)

        # ── Outer wrapper ─────────────────────────────────────────────────────
        ol = QVBoxLayout(self)
        ol.setContentsMargins(0, 0, 0, 0)
        ol.setSpacing(0)
        ol.addWidget(self._frame)

        self._recalc()

        # ── Signals ───────────────────────────────────────────────────────────
        self._edit.document().documentLayout().documentSizeChanged.connect(
            self._on_doc_changed
        )
        self._edit.installEventFilter(self)

    # ── Focus border ──────────────────────────────────────────────────────────
    def eventFilter(self, obj, event):
        if obj is self._edit:
            if event.type() == QEvent.FocusIn:
                self._frame.setStyleSheet(self._SS_FOCUS.format(r=self._RADIUS))
            elif event.type() == QEvent.FocusOut:
                self._frame.setStyleSheet(self._SS_NORMAL.format(r=self._RADIUS))
        return super().eventFilter(obj, event)

    # ── pyuic5 compatibility stubs ─────────────────────────────────────────────
    # mainUI.py (auto-generated) calls these QTextEdit / QFrame methods.
    # We silently ignore them so the app works even with a fresh pyuic5 run.
    def setFrameShape(self, *a):       pass
    def setFrameShadow(self, *a):      pass
    def setSizeAdjustPolicy(self, *a): pass
    def setText(self, *a):             pass   # retranslateUi calls this; ignore
    def setHtml(self, html: str):
        # retranslateUi also calls setHtml with the initial placeholder HTML.
        # We ignore the HTML but keep the placeholder text already set.
        pass

    # ── QTextEdit-compatible public API ───────────────────────────────────────
    def toPlainText(self) -> str:
        return self._edit.toPlainText()

    def clear(self):
        self._edit.clear()
        self._edit.setFont(self._edit._default_font)
        self._set_edit_h(self._TEXT_MIN)

    def reset_height(self):
        """Snap back to minimum height — call after clear()."""
        self._set_edit_h(self._TEXT_MIN)

    def setPlaceholderText(self, text: str):
        self._edit.setPlaceholderText(text)

    def setFocus(self):
        self._edit.setFocus()

    def toHtml(self) -> str:
        return self._edit.toHtml()

    # ── Loading chip API ──────────────────────────────────────────────────────
    def show_loading(self, filename: str = ""):
        """Insert a spinning loading chip into the strip."""
        self._remove_loading_chip()
        chip = _LoadingChip(self.GIF_PATH, filename, parent=self._strip)
        self._strip_layout.insertWidget(0, chip)
        self._loading_chip = chip
        self._strip.setFixedHeight(self._CHIP_H)
        self._strip.show()
        self._recalc()

    def hide_loading(self):
        """Remove the loading chip; hide strip if no attachment either."""
        self._remove_loading_chip()
        if self._chip is None:
            self._strip.hide()
        self._recalc()

    def _remove_loading_chip(self):
        if self._loading_chip:
            self._loading_chip.stop()
            self._loading_chip.setParent(None)
            self._loading_chip = None

    # ── Attachment chip API ───────────────────────────────────────────────────
    def set_attachment(self, attachment: dict):
        """
        Show an attachment chip.
        Pass None to remove the chip and hide the strip.
        Dict keys used: "filename" (str), "pixmap" (QPixmap | None).
        """
        if self._chip:
            self._chip.setParent(None)
            self._chip = None

        self._attachment = attachment

        # Clear previous attachment widgets in strip (keep loading chip if any)
        if attachment:
            chip = _AttachChip(
                attachment["filename"],
                attachment.get("pixmap"),
                parent=self._strip,
            )
            chip.remove_requested.connect(self._on_chip_remove)
            # Insert after loading chip (index 0 if no loading, else index 1)
            insert_idx = 1 if self._loading_chip else 0
            self._strip_layout.insertWidget(insert_idx, chip)
            self._chip = chip
            self._strip.show()
        else:
            if self._loading_chip is None:
                self._strip.hide()

        self._recalc()

    def _on_chip_remove(self):
        self.set_attachment(None)
        win = self.window()
        if win and hasattr(win, "attached_document"):
            win.attached_document = None
            try:
                from services.handle_requests import _set_attach_button_inactive
                _set_attach_button_inactive(win)
            except ImportError:
                pass

    # ── Height helpers ────────────────────────────────────────────────────────
    def _on_doc_changed(self, _=None):
        doc_h = self._edit.document().size().height()
        cm    = self._edit.contentsMargins()
        raw   = int(doc_h + cm.top() + cm.bottom() + 6)
        self._set_edit_h(max(self._TEXT_MIN, min(raw, self._TEXT_MAX)))

    def _set_edit_h(self, h: int):
        if self._edit.height() != h:
            self._edit.setFixedHeight(h)
        self._recalc()

    def _recalc(self):
        cm = self._flayout.contentsMargins()
        strip_h = (self._CHIP_H + self._STRIP_GAP) if not self._strip.isHidden() else 0
        # Total = top_pad + [strip + gap] + edit + btn_gap + btn_row + bottom_pad + borders
        total = (cm.top()
                 + strip_h
                 + self._edit.height()
                 + self._BTN_ROW_GAP
                 + self._BTN_H
                 + cm.bottom()
                 + 4)   # 2px border top + bottom
        self.setFixedHeight(total)
        self.height_changed.emit(total)