# PYTHON VERSION : 3.8.0
# PLATFORM : Windows 11 Pro 22H2
#
# This is the main executable file for the whole project, 
# Do not edit this file unless you know what you are doing.


# importing necessary packages and modules ------------------------------
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys, threading
from termcolor import colored

from ui.mainUI import Ui_MainWindow

from auth.logout import LogOutService

from services.handle_requests import (run_login, 
                                      verify_token, 
                                      save_user_preferences, 
                                      get_user_preferences, 
                                      send_prompt,
                                      open_document,
                                      stop_prompt,
                                      load_chat_history,
                                      on_chat_history_item_clicked,
                                      _show_chat_context_menu)

from ui_controllers.ui_functions import UIFunctions

from ui.widgets.chat_area import ChatArea
# -------------------------------------------------------------------------


class MainWindow(QMainWindow) :
    def __init__(self):
        QMainWindow.__init__(self)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
 
        # ── Hide the external StickyButton siblings ────────────────────────────
        # The new AutoGrowTextEdit has add_btn + search_btn built in at the
        # bottom of the frame.  The mainUI.py siblings are no longer needed.
        self.ui.addButton.hide()
        self.ui.searchButton.hide()
        self.ui.addButton_2.hide()
        self.ui.searchButton_2.hide()
 
        # ── Unlock conversation-page input frame ───────────────────────────────
        self.ui.frame_2.setMinimumHeight(60)
        self.ui.frame_2.setMaximumHeight(16777215)
        self.ui.text_prompt.setMaximumHeight(16777215)
        self.ui.text_prompt_2.setMaximumHeight(16777215)
 
        # Add bottom margin so the input isn't flush with the window edge
        self.ui.verticalLayout_18.setContentsMargins(0, 0, 0, 12)
 
        # Grow conversation input upward: frame_2 height tracks text_prompt_2
        def _on_conv_input_h(h: int):
            self.ui.frame_2.setFixedHeight(h + 16)
        self.ui.text_prompt_2.height_changed.connect(_on_conv_input_h)
 
        # ── Chat area ──────────────────────────────────────────────────────────
        self.chat_area = ChatArea()
        self.ui.chat_layout.addWidget(self.chat_area)
 
        self.ui_functions = UIFunctions(self)
        self.ui_functions.uiDefinitions()
 
        # No document attached at startup
        self.attached_document = None
 
        # ── Connect internal add buttons (ONE connection each, no duplicates) ──
        self.ui.text_prompt.add_btn.clicked.connect(
            lambda: open_document(self)
        )
        self.ui.text_prompt_2.add_btn.clicked.connect(
            lambda: open_document(self)
        )
 
        # ── Connect internal search buttons ────────────────────────────────────
        self.ui.text_prompt.search_btn.clicked.connect(
            lambda: self.send_user_prompt()
        )
        self.ui.text_prompt_2.search_btn.clicked.connect(
            lambda: self._handle_search_or_stop()
        )
 
        # ── Sidebar / navigation ───────────────────────────────────────────────
        self.ui.label_7.setVisible(False)
        self.ui.chat_history.setVisible(False)
        self.ui.button_save.setEnabled(False)
 
        def MoveWindow(event):
            if self.ui_functions.returnStatus() == 1:
                self.ui_functions.maximize_restore()
            if event.buttons() == Qt.LeftButton:
                self.move(self.pos() + event.globalPos() - self.dragpos)
                self.dragpos = event.globalPos()
                event.accept()
 
        self.ui.status_bar.mouseMoveEvent = MoveWindow
 
        self.ui.toggle_button.clicked.connect(
            lambda: self.ui_functions.toggle(275, True))
        self.ui.button_new_chat.clicked.connect(
            lambda: self.ui_functions.setNewChatPage())
        self.ui.button_settings.clicked.connect(
            lambda: self.ui_functions.setSettingsPage())
        self.ui.buttonAbout.clicked.connect(
            lambda: self.ui_functions.setAboutPage())
        self.ui.acc_button.clicked.connect(
            lambda: self.ui_functions.setAccountPage())
        self.ui.button_preferences.clicked.connect(
            lambda: self.ui_functions.setPreferencesPage())
        self.ui.button_logout.clicked.connect(
            lambda: self.invoke_logout())
        self.ui.login_button.clicked.connect(
            lambda: run_login(self))
        self.ui.button_save.clicked.connect(
            lambda: self.handle_user_preferences())
        self.ui.button_new_chat.clicked.connect(self.handle_new_chat)
 
        self.ui.chat_history.itemClicked.connect(
            lambda item: on_chat_history_item_clicked(self, item))
        self.ui.chat_history.setStyleSheet("""
            QListWidget {
                background: transparent; border: none;
                color: rgba(255,255,255,160);
                font-family: 'Roboto'; font-size: 10pt;
            }
            QListWidget::item { padding: 8px 12px; border-radius: 6px; }
            QListWidget::item:hover {
                background-color: rgb(55, 62, 76);
                color: rgba(255,255,255,220);
            }
            QListWidget::item:selected {
                background-color: rgb(48, 85, 140); color: white;
            }
        """)
        self.ui.chat_history.setContextMenuPolicy(Qt.CustomContextMenu)
        self.ui.chat_history.customContextMenuRequested.connect(
            lambda pos: _show_chat_context_menu(self, pos))
    
        
    def keyPressEvent(self, event):
        if event.key() in (Qt.Key_Return, Qt.Key_Enter):
            if event.modifiers() == Qt.ShiftModifier:
                # Shift+Enter → newline
                super().keyPressEvent(event)
            else:
                # Enter → submit
                self.send_user_prompt()
                return
        else:
            super().keyPressEvent(event)
      
        
    def mousePressEvent(self, event) :
        self.dragpos = event.globalPos()
        

    def get_threads(self) :
        total_threads = threading.activeCount()
        print(colored("Total active threads : {}".format(total_threads), 'green'))
        
    def handle_user_preferences(self):
        save_user_preferences(self)

    def update_user_preferences(self): 
        get_user_preferences(self)
        
    def invoke_logout(self):
        if self.ui.button_logout.text() == 'Log In':
            run_login(self)
        if self.ui.button_logout.text() == 'Log Out':
            self.service = LogOutService(self)
            self.service.LogOut()
        
    def send_user_prompt(self):
        send_prompt(self)
        
    def clear_chat(self):
        layout = self.ui.chat_layout   # or self.chat_layout if defined inside
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.deleteLater()
                
        self.chat_area = ChatArea()
        self.ui.chat_layout.addWidget(self.chat_area)

    def handle_new_chat(self):
        # clear UI
        self.clear_chat()

        # reset session/chat
        self.current_chat_id = None
        self.session_id = None

        # reset streaming buffer
        if hasattr(self, "full_text"):
            del self.full_text

        self._scroll_pending = False
        
        # Also clear any attached document when starting a new chat
        self.attached_document = None
        from services.handle_requests import _set_attach_button_inactive
        _set_attach_button_inactive(self)
        
    def _handle_search_or_stop(self):
        """Toggle: if streaming → stop, else → send."""
        if getattr(self, '_is_streaming', False):
            stop_prompt(self)
            self._is_streaming = False
        else:
            self.send_user_prompt()

def main():
    app = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()

    # main_window.run_login()
    # MainWindow.verify_token(main_window)
    
    verify_token(main_window)

    # ==>> Update User settings when reopen application 
    # main_window.update_user_preferences()
    
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()   


