# PYTHON VERSION : 3.8.0
# PLATFORM : Windows 11 Pro 22H2
#
# This is the main executable file for the whole project, 
# Do not edit this file unless you know what you are doing.


# importing necessary packages and modules ------------------------------
from PyQt5.QtCore import Qt
from PyQt5.QtWidgets import QMainWindow, QApplication
import sys, threading
from termcolor import colored

from ui.mainUI import Ui_MainWindow

from auth.logout import LogOutService

from services.handle_requests import (run_login, 
                                      verify_token, 
                                      save_user_preferences, 
                                      get_user_preferences, 
                                      send_prompt,
                                      stop_prompt,
                                      load_chat_history,
                                      on_chat_history_item_clicked)

from ui_controllers.ui_functions import UIFunctions

from ui.widgets.chat_area import ChatArea
# -------------------------------------------------------------------------


class MainWindow(QMainWindow) :
    def __init__(self) :
        QMainWindow.__init__(self)
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)
        
        self.chat_area = ChatArea()
        self.ui.chat_layout.addWidget(self.chat_area)
        
        self.ui_functions = UIFunctions(self)
        self.ui_functions.uiDefinitions()
        

        # Attach button to text edit
        self.ui.searchButton.setTextEdit(self.ui.text_prompt)
        self.ui.searchButton.setAnchor("bottom-right")

        self.ui.addButton.setTextEdit(self.ui.text_prompt)
        self.ui.addButton.setAnchor("bottom-left")
        
        # "Recent chats" label set hidden initially
        self.ui.label_7.setVisible(False)

        # The chat history list set hidden initialy
        self.ui.chat_history.setVisible(False)
        
        # update preferences onle when user is logged in
        self.ui.button_save.setEnabled(False)
        
        def MoveWindow(event) :
            
            # ==>> Restore before move
            if self.ui_functions.returnStatus() == 1 :
                self.ui_functions.maximize_restore()
            
            # ==>> Move Window when left button is clicked and dragged
            if event.buttons() == Qt.LeftButton :
                self.move(self.pos() + event.globalPos() - self.dragpos)
                self.dragpos = event.globalPos()
                event.accept()   

        # ==>> Move Window
        self.ui.status_bar.mouseMoveEvent = MoveWindow 


        # ==>> Page toggle and Strips color function calling
        self.ui.toggle_button.clicked.connect(lambda: self.ui_functions.toggle(275, True))
        self.ui.button_new_chat.clicked.connect(lambda: self.ui_functions.setNewChatPage())
        self.ui.button_settings.clicked.connect(lambda: self.ui_functions.setSettingsPage())
        self.ui.buttonAbout.clicked.connect(lambda: self.ui_functions.setAboutPage())
        self.ui.acc_button.clicked.connect(lambda: self.ui_functions.setAccountPage())
        self.ui.button_preferences.clicked.connect(lambda: self.ui_functions.setPreferencesPage())
        self.ui.button_logout.clicked.connect(lambda: self.invoke_logout())
        self.ui.login_button.clicked.connect(lambda: run_login(self))
        
        self.ui.button_save.clicked.connect(lambda: self.handle_user_preferences())
        self.ui.searchButton.clicked.connect(lambda: self.send_user_prompt())
        self.ui.searchButton_2.clicked.connect(lambda: self.send_user_prompt())
        
        self.ui.button_new_chat.clicked.connect(self.handle_new_chat)
    
        # self.ui.searchButton.clicked.connect(lambda: self._handle_search_or_stop())
        self.ui.searchButton_2.clicked.connect(lambda: self._handle_search_or_stop())
        
        self.ui.chat_history.itemClicked.connect(lambda item: on_chat_history_item_clicked(self, item))
        
        # style the list widget so it fits the dark sidebar
        self.ui.chat_history.setStyleSheet("""
            QListWidget {
                background: transparent;
                border: none;
                color: rgba(255,255,255,160);
                font-family: 'Roboto';
                font-size: 10pt;
            }
            QListWidget::item {
                padding: 8px 12px;
                border-radius: 6px;
            }
            QListWidget::item:hover {
                background-color: rgb(55, 62, 76);
                color: rgba(255,255,255,220);
            }
            QListWidget::item:selected {
                background-color: rgb(48, 85, 140);
                color: white;
            }
        """)
    
        
    def keyPressEvent(self, event):
        if event.key() in (Qt.Key_Return, Qt.Key_Enter):
            if event.modifiers() == Qt.ShiftModifier:
                # Shift+Enter → newline
                super().keyPressEvent(event)
            else:
                # Enter → submit
                self.send_user_prompt()
                return
        else:
            super().keyPressEvent(event)
      
        
    def mousePressEvent(self, event) :
        self.dragpos = event.globalPos()
        

    def get_threads(self) :
        total_threads = threading.activeCount()
        print(colored("Total active threads : {}".format(total_threads), 'green'))
        
    def handle_user_preferences(self):
        save_user_preferences(self)

    def update_user_preferences(self): 
        get_user_preferences(self)
        
    def invoke_logout(self):
        if self.ui.button_logout.text() == 'Log In':
            run_login(self)
        if self.ui.button_logout.text() == 'Log Out':
            self.service = LogOutService(self)
            self.service.LogOut()
        
    def send_user_prompt(self):
        send_prompt(self)
        
    def clear_chat(self):
        layout = self.ui.chat_layout   # or self.chat_layout if defined inside
        while layout.count():
            item = layout.takeAt(0)
            widget = item.widget()
            if widget:
                widget.deleteLater()
                
        self.chat_area = ChatArea()
        self.ui.chat_layout.addWidget(self.chat_area)

    def handle_new_chat(self):
        # clear UI
        self.clear_chat()

        # reset session/chat
        self.current_chat_id = None
        self.session_id = None

        # reset streaming buffer
        if hasattr(self, "full_text"):
            del self.full_text

        self._scroll_pending = False
        
    def _handle_search_or_stop(self):
        """Toggle: if streaming → stop, else → send."""
        if getattr(self, '_is_streaming', False):
            stop_prompt(self)
            self._is_streaming = False
        else:
            self.send_user_prompt()

def main():
    app = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()

    # main_window.run_login()
    # MainWindow.verify_token(main_window)
    
    verify_token(main_window)

    # ==>> Update User settings when reopen application 
    # main_window.update_user_preferences()
    
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()   


