# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(480, 760)
        MainWindow.setMinimumSize(QtCore.QSize(480, 760))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("QFrame{\n"
"    border-radius:10px;\n"
"}")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.drop_shadow_frame)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("background-color:rgb(29, 32, 38);\n"
"border-bottom-left-radius:0px;\n"
"border-bottom-right-radius:0px;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.frame_5)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 38))
        self.pushButton.setMaximumSize(QtCore.QSize(16777215, 38))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(185, 185, 185);\n"
"text-align: left;\n"
"padding-left:15px;")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Reqs/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(25, 25))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.horizontalLayout.addWidget(self.frame_5)
        self.button_close = QtWidgets.QPushButton(self.frame)
        self.button_close.setMinimumSize(QtCore.QSize(0, 0))
        self.button_close.setMaximumSize(QtCore.QSize(60, 40))
        self.button_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    border-top-right-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(232, 0, 116)\n"
"}")
        self.button_close.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Reqs/close-24 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon1)
        self.button_close.setIconSize(QtCore.QSize(25, 25))
        self.button_close.setObjectName("button_close")
        self.horizontalLayout.addWidget(self.button_close)
        self.verticalLayout_2.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.drop_shadow_frame)
        self.frame_2.setStyleSheet("border-top-left-radius:0px;\n"
"border-top-right-radius:0px;")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_2)
        self.stackedWidget.setGeometry(QtCore.QRect(0, 0, 480, 720))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.signup_page = QtWidgets.QWidget()
        self.signup_page.setObjectName("signup_page")
        self.frame_3 = QtWidgets.QFrame(self.signup_page)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 480, 720))
        self.frame_3.setStyleSheet("background-color:rgb(27, 29, 35)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label = QtWidgets.QLabel(self.frame_3)
        self.label.setGeometry(QtCore.QRect(10, 60, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgba(255, 255, 255, 180);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.email_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.email_lineEdit.setGeometry(QtCore.QRect(120, 210, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.email_lineEdit.setFont(font)
        self.email_lineEdit.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37,39,48);\n"
"       border-radius:20px;\n"
"    background-color:rgb(34,36,44);\n"
"    color:#FFF;\n"
"    padding-left:25px;\n"
"    padding-right:25px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.email_lineEdit.setText("")
        self.email_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.email_lineEdit.setObjectName("email_lineEdit")
        self.pass_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.pass_lineEdit.setGeometry(QtCore.QRect(120, 270, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pass_lineEdit.setFont(font)
        self.pass_lineEdit.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37,39,48);\n"
"       border-radius:20px;\n"
"    background-color:rgb(34,36,44);\n"
"    color:#FFF;\n"
"    padding-left:25px;\n"
"    padding-right:25px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.pass_lineEdit.setText("")
        self.pass_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pass_lineEdit.setObjectName("pass_lineEdit")
        self.signup_button = QtWidgets.QPushButton(self.frame_3)
        self.signup_button.setGeometry(QtCore.QRect(180, 390, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.signup_button.setFont(font)
        self.signup_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.signup_button.setStyleSheet("QPushButton{\n"
"      border-radius:16px;\n"
"      border:2px solid rgb(37,39,48);\n"
"      background-color:rgb(34,36,44);\n"
"      color:rgb(85,170,255);\n"
"      font-size:9pt;\n"
"}\n"
"QPushButton:hover{\n"
"      border:2px solid rgb(114, 254, 120);\n"
"}")
        self.signup_button.setObjectName("signup_button")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(120, 580, 181, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgba(255, 255, 255, 230);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.login_page_button = QtWidgets.QPushButton(self.frame_3)
        self.login_page_button.setGeometry(QtCore.QRect(300, 580, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.login_page_button.setFont(font)
        self.login_page_button.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"    background:none;\n"
"}")
        self.login_page_button.setObjectName("login_page_button")
        self.info_label = QtWidgets.QLabel(self.frame_3)
        self.info_label.setGeometry(QtCore.QRect(90, 320, 301, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(8)
        self.info_label.setFont(font)
        self.info_label.setStyleSheet("color:rgb(255, 0, 0);")
        self.info_label.setText("")
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label.setWordWrap(True)
        self.info_label.setObjectName("info_label")
        self.name_lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.name_lineEdit.setGeometry(QtCore.QRect(120, 150, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.name_lineEdit.setFont(font)
        self.name_lineEdit.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37,39,48);\n"
"       border-radius:20px;\n"
"    background-color:rgb(34,36,44);\n"
"    color:#FFF;\n"
"    padding-left:25px;\n"
"    padding-right:25px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.name_lineEdit.setText("")
        self.name_lineEdit.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.stackedWidget.addWidget(self.signup_page)
        self.login_page = QtWidgets.QWidget()
        self.login_page.setObjectName("login_page")
        self.frame_4 = QtWidgets.QFrame(self.login_page)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 480, 720))
        self.frame_4.setStyleSheet("background-color:rgb(27, 29, 35)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_3 = QtWidgets.QLabel(self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 60, 461, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgba(255, 255, 255, 180);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.uid_lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.uid_lineEdit_2.setGeometry(QtCore.QRect(120, 190, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.uid_lineEdit_2.setFont(font)
        self.uid_lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37,39,48);\n"
"       border-radius:20px;\n"
"    background-color:rgb(34,36,44);\n"
"    color:#FFF;\n"
"    padding-left:25px;\n"
"    padding-right:25px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.uid_lineEdit_2.setText("")
        self.uid_lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.uid_lineEdit_2.setObjectName("uid_lineEdit_2")
        self.pass_lineEdit_2 = QtWidgets.QLineEdit(self.frame_4)
        self.pass_lineEdit_2.setGeometry(QtCore.QRect(120, 250, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.pass_lineEdit_2.setFont(font)
        self.pass_lineEdit_2.setStyleSheet("QLineEdit{\n"
"    border:2px solid rgb(37,39,48);\n"
"       border-radius:20px;\n"
"    background-color:rgb(34,36,44);\n"
"    color:#FFF;\n"
"    padding-left:25px;\n"
"    padding-right:25px;\n"
"}\n"
"QLineEdit:hover{\n"
"    border:2px solid rgb(48,50,62);\n"
"}\n"
"QLineEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.pass_lineEdit_2.setText("")
        self.pass_lineEdit_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.pass_lineEdit_2.setObjectName("pass_lineEdit_2")
        self.login_button = QtWidgets.QPushButton(self.frame_4)
        self.login_button.setGeometry(QtCore.QRect(180, 390, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("QPushButton{\n"
"      border-radius:16px;\n"
"      border:2px solid rgb(37,39,48);\n"
"      background-color:rgb(34,36,44);\n"
"      color:rgb(85,170,255);\n"
"      font-size:9pt;\n"
"}\n"
"QPushButton:hover{\n"
"      /*border:2px solid rgb(114, 254, 120); */\n"
"    border: 2px solid rgb(231, 0, 116);\n"
"}")
        self.login_button.setObjectName("login_button")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(120, 580, 171, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgba(255, 255, 255, 230);")
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.signup_page_button = QtWidgets.QPushButton(self.frame_4)
        self.signup_page_button.setGeometry(QtCore.QRect(290, 580, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.signup_page_button.setFont(font)
        self.signup_page_button.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 170, 255);\n"
"    border:none;\n"
"    background:none;\n"
"}")
        self.signup_page_button.setObjectName("signup_page_button")
        self.info_label2 = QtWidgets.QLabel(self.frame_4)
        self.info_label2.setGeometry(QtCore.QRect(120, 300, 301, 31))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(8)
        self.info_label2.setFont(font)
        self.info_label2.setStyleSheet("color:rgb(255, 0, 0);")
        self.info_label2.setText("")
        self.info_label2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.info_label2.setObjectName("info_label2")
        self.stackedWidget.addWidget(self.login_page)
        self.verticalLayout_2.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        # MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", " AI Personalized Learning App"))
        self.label.setText(_translate("MainWindow", "SIGN UP"))
        self.email_lineEdit.setPlaceholderText(_translate("MainWindow", "Email"))
        self.pass_lineEdit.setPlaceholderText(_translate("MainWindow", "Password"))
        self.signup_button.setText(_translate("MainWindow", "Sign Up"))
        self.label_2.setText(_translate("MainWindow", "Already have an account ?"))
        self.login_page_button.setText(_translate("MainWindow", "Log in"))
        self.name_lineEdit.setPlaceholderText(_translate("MainWindow", "Full Name"))
        self.label_3.setText(_translate("MainWindow", "Log In"))
        self.uid_lineEdit_2.setPlaceholderText(_translate("MainWindow", "Username"))
        self.pass_lineEdit_2.setPlaceholderText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.label_4.setText(_translate("MainWindow", "Don\'t have an account ?"))
        self.signup_page_button.setText(_translate("MainWindow", "Sign Up"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
