# PYTHON VERSION : 3.8.0
# PLATFORM : Windows 11 Pro 22H2
#
# This is the main executable file for the whole SIH project, 
# Do not edit this file unless you know what you are doing.



# importing necessary packages and modules ------------------------------
from PyQt5 import QtWidgets, QtCore, QtGui
from PyQt5.QtCore import Qt, QRect, QPropertyAnimation, QThread, pyqtSignal, QPoint, pyqtSlot, QTimer
from PyQt5.QtWidgets import *
import sys, threading, time
from termcolor import colored
import subprocess

# importing Main UI
from mainUI import Ui_MainWindow

# -------------------------------------------------------------------------


class MainWindow(QMainWindow) :
    def __init__(self) :
        QMainWindow.__init__(self)
        from ui_functions import UIFunctions
        
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self)

        # Attach button to text edit
        self.ui.searchButton.setTextEdit(self.ui.text_prompt)
        self.ui.searchButton.setAnchor("bottom-right")

        self.ui.addButton.setTextEdit(self.ui.text_prompt)
        self.ui.addButton.setAnchor("bottom-left")
        
        def MoveWindow(event) :
            
            # ==>> Restore before move
            if UIFunctions.returnStatus(self) == 1 :
                UIFunctions.maximize_restore(self)
            
            # ==>> Move Window when left button is clicked and dragged
            if event.buttons() == Qt.LeftButton :
                self.move(self.pos() + event.globalPos() - self.dragpos)
                self.dragpos = event.globalPos()
                event.accept()   

        # ==>> Move Window
        self.ui.status_bar.mouseMoveEvent = MoveWindow

        # ==>> UI functions and removing title bar
        UIFunctions.uiDefinitions(self)       


        # ==>> Page toggle and Strips color function calling
        self.ui.toggle_button.clicked.connect(lambda: UIFunctions.toggle(self, 275, True))
        self.ui.button_new_chat.clicked.connect(lambda: UIFunctions.setNewChatPage(self))
        self.ui.button_settings.clicked.connect(lambda: UIFunctions.setSettingsPage(self))
        
        self.ui.button_save.clicked.connect(lambda: self.handle_user_preferences())
        self.ui.searchButton.clicked.connect(lambda: self.send_user_prompt())
    
        # self.ui.settings_button.clicked.connect(lambda: UIFunctions.Settings_Page(self))
        # self.ui.settings_button_2.clicked.connect(lambda: UIFunctions.Settings_Page(self))  
        
    def keyPressEvent(self, event):
        if event.key() in (Qt.Key_Return, Qt.Key_Enter):
            if event.modifiers() == Qt.ShiftModifier:
                # Shift+Enter → newline
                super().keyPressEvent(event)
            else:
                # Enter → submit
                self.send_user_prompt()
                return
        else:
            super().keyPressEvent(event)
      
        
    def mousePressEvent(self, event) :
        self.dragpos = event.globalPos()

    def get_threads(self) :
        total_threads = threading.activeCount()
        print(colored("Total active threads : {}".format(total_threads), 'green'))
        
    def handle_user_preferences(self):
        from handle_requests import save_user_preferences
        save_user_preferences(self)

    def update_user_preferences(self):
        from handle_requests import get_user_preferences
        get_user_preferences(self)
        
        
    def send_user_prompt(self):
        from handle_requests import send_prompt
        send_prompt(self)

    
def run_login(main_window, forced=None):
    # importing Login UI
    from login_window import LoginWindow, BlurOverlay
    subprocess.run(
        ["icacls", "auth_token.x", "/remove:d", "Everyone"],
        check=True
    )

    with open("auth_token.x", "r") as token_file:
        token = token_file.read()

    if not token or forced:
        login = LoginWindow(main_window)
        login.exec_()

    subprocess.run(
        ["icacls", "auth_token.x", "/deny", "Everyone:(R)"],
        check=True
    )


def main():
    app = QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()

    run_login(main_window)

    # ==>> Update User settings when reopen application 
    main_window.update_user_preferences()
    
    sys.exit(app.exec_())


if __name__ == "__main__":
    main()   


