# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1480, 759)
        MainWindow.setStyleSheet("QMainWindow{\n"
"    background-color: rgb(45, 45, 45);\n"
"    border-radius:10px;\n"
"}\n"
"\n"
"/* Styles for the vertical scrollbar */\n"
"\n"
"QScrollBar:vertical {\n"
"    border-radius:4px;\n"
"    background-color: rgb(60, 60, 91);/* #F0F0F0; */\n"
"    width: 8px;\n"
"    margin: 0px 0px 20px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    /*background-color: #4F9FFE;*/\n"
"    background-color:rgb(80, 80, 122);\n"
"    border-radius:4px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    /*background-color: #4F9FFE;*/\n"
"    /*background-color: rgb(170, 0, 255);*/\n"
"    background-color:rgb(0, 128, 255);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: bottom;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"    subcontrol-position: top;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"\n"
"/*stylesheet for horizontal scrollbar*/\n"
"\n"
"\n"
"QScrollBar:horizontal {\n"
"    border-radius:5px;\n"
"    background-color: rgb(60, 60, 91);/* #F0F0F0; */\n"
"    width: 12px;\n"
"    margin: 0px 0px 0px 0px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal {\n"
"    /*background-color: #4F9FFE;*/\n"
"    background-color:rgb(80, 80, 122);\n"
"    border-radius:5px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QScrollBar::handle:horizontal:hover {\n"
"    /*background-color: #4F9FFE;*/\n"
"    background-color: rgb(170, 0, 255);;\n"
"}\n"
"\n"
"QScrollBar::add-line:horizontal {\n"
"    height: 0px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::sub-line:horizontal {\n"
"    height: 0px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"\n"
"QScrollBar::left-arrow:horizontal, QScrollBar::right-arrow:horizontal {\n"
"    width: 0px;\n"
"    height: 0px;\n"
"    background: none;\n"
"}\n"
"\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {\n"
"    background: none;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("border-radius:10px;")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.drop_shadow_frame = QtWidgets.QFrame(self.centralwidget)
        self.drop_shadow_frame.setStyleSheet("QFrame{\n"
"    border-radius:10px;\n"
"}")
        self.drop_shadow_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.drop_shadow_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.drop_shadow_frame.setObjectName("drop_shadow_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.drop_shadow_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Top_Bar = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("QFrame{\n"
"    background-color: rgb(38, 42, 52);\n"
"}")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.toggle_frame = QtWidgets.QFrame(self.Top_Bar)
        self.toggle_frame.setMaximumSize(QtCore.QSize(85, 16777215))
        self.toggle_frame.setStyleSheet("QFrame{\n"
"    border-radius:0px;\n"
"    border-top-left-radius:10px;\n"
"}\n"
"QFrame:hover{\n"
"    background-color: rgba(79, 159, 254, 220);\n"
"}")
        self.toggle_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toggle_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggle_frame.setObjectName("toggle_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.toggle_frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toggle_button = QtWidgets.QPushButton(self.toggle_frame)
        self.toggle_button.setMinimumSize(QtCore.QSize(0, 40))
        self.toggle_button.setMaximumSize(QtCore.QSize(80, 16777215))
        self.toggle_button.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:none;\n"
"}")
        self.toggle_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Reqs/menu-50 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggle_button.setIcon(icon)
        self.toggle_button.setIconSize(QtCore.QSize(25, 25))
        self.toggle_button.setObjectName("toggle_button")
        self.horizontalLayout_2.addWidget(self.toggle_button)
        self.horizontalLayout.addWidget(self.toggle_frame)
        self.top_bar_frame = QtWidgets.QFrame(self.Top_Bar)
        self.top_bar_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar_frame.setObjectName("top_bar_frame")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.top_bar_frame)
        self.horizontalLayout_5.setContentsMargins(10, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.icon = QtWidgets.QPushButton(self.top_bar_frame)
        self.icon.setMinimumSize(QtCore.QSize(0, 35))
        self.icon.setMaximumSize(QtCore.QSize(40, 16777215))
        self.icon.setStyleSheet("background-color: rgb(38, 42, 52);\n"
"border:none;")
        self.icon.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../Reqs/app_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.icon.setIcon(icon1)
        self.icon.setIconSize(QtCore.QSize(27, 27))
        self.icon.setObjectName("icon")
        self.horizontalLayout_5.addWidget(self.icon)
        self.status_bar = QtWidgets.QLabel(self.top_bar_frame)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(9)
        self.status_bar.setFont(font)
        self.status_bar.setStyleSheet("color: rgb(220, 220, 220);")
        self.status_bar.setObjectName("status_bar")
        self.horizontalLayout_5.addWidget(self.status_bar)
        self.horizontalLayout.addWidget(self.top_bar_frame)
        self.top_bar_button_frame = QtWidgets.QFrame(self.Top_Bar)
        self.top_bar_button_frame.setMinimumSize(QtCore.QSize(200, 0))
        self.top_bar_button_frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.top_bar_button_frame.setStyleSheet("border-radius:0px;\n"
"border-top-right-radius:10px;\n"
"")
        self.top_bar_button_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_bar_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_bar_button_frame.setObjectName("top_bar_button_frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_bar_button_frame)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.button_minimize = QtWidgets.QPushButton(self.top_bar_button_frame)
        self.button_minimize.setMinimumSize(QtCore.QSize(0, 40))
        self.button_minimize.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:none;\n"
"    border-radius:0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(45, 50, 62);\n"
"}")
        self.button_minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("../Reqs/subtract-24 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_minimize.setIcon(icon2)
        self.button_minimize.setObjectName("button_minimize")
        self.horizontalLayout_3.addWidget(self.button_minimize)
        self.button_restore = QtWidgets.QPushButton(self.top_bar_button_frame)
        self.button_restore.setMinimumSize(QtCore.QSize(0, 40))
        self.button_restore.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:none;\n"
"    border-radius:0px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:  rgb(45, 50, 62);\n"
"}")
        self.button_restore.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("../Reqs/maximize.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_restore.setIcon(icon3)
        self.button_restore.setObjectName("button_restore")
        self.horizontalLayout_3.addWidget(self.button_restore)
        self.button_close = QtWidgets.QPushButton(self.top_bar_button_frame)
        self.button_close.setMinimumSize(QtCore.QSize(0, 40))
        self.button_close.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    background:none;\n"
"    border-radius:0px;\n"
"    border-top-right-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(212, 58, 212)\n"
"}")
        self.button_close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("../Reqs/close-24 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_close.setIcon(icon4)
        self.button_close.setObjectName("button_close")
        self.horizontalLayout_3.addWidget(self.button_close)
        self.horizontalLayout.addWidget(self.top_bar_button_frame)
        self.verticalLayout_2.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.drop_shadow_frame)
        self.Content.setStyleSheet("border-bottom-left-radius:10px;\n"
"border-bottom-right-radius:10px;")
        self.Content.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.toggle_frame_left = QtWidgets.QFrame(self.Content)
        self.toggle_frame_left.setMinimumSize(QtCore.QSize(220, 0))
        self.toggle_frame_left.setMaximumSize(QtCore.QSize(85, 16777215))
        self.toggle_frame_left.setStyleSheet("background-color: #272C36;\n"
"border-radius:0px;\n"
"border-bottom-left-radius:10px;\n"
"")
        self.toggle_frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toggle_frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toggle_frame_left.setObjectName("toggle_frame_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.toggle_frame_left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_status = QtWidgets.QFrame(self.toggle_frame_left)
        self.frame_status.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_status.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_status.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_status.setStyleSheet("QFrame{\n"
"    border-radius: 0px;\n"
"    border-bottom: 1px solid rgba(255, 255, 255, 30);\n"
"}\n"
"QFrame:hover{\n"
"    background-color: rgb(55, 62, 76);\n"
"    border:2px solid rgba(0, 159, 238, 140);\n"
"    border-radius:5px;\n"
"}")
        self.frame_status.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_status.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_status.setObjectName("frame_status")
        self.button_new_chat = QtWidgets.QPushButton(self.frame_status)
        self.button_new_chat.setGeometry(QtCore.QRect(5, 0, 231, 50))
        self.button_new_chat.setMinimumSize(QtCore.QSize(70, 50))
        self.button_new_chat.setMaximumSize(QtCore.QSize(16777215, 50))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.button_new_chat.setFont(font)
        self.button_new_chat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_new_chat.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.button_new_chat.setStyleSheet("background:none;\n"
"border:none;\n"
"color: rgba(255, 255, 255, 180);")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("../Reqs/new_chat.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_new_chat.setIcon(icon5)
        self.button_new_chat.setIconSize(QtCore.QSize(35, 35))
        self.button_new_chat.setObjectName("button_new_chat")
        self.verticalLayout_3.addWidget(self.frame_status)
        self.label_7 = QtWidgets.QLabel(self.toggle_frame_left)
        self.label_7.setMinimumSize(QtCore.QSize(0, 40))
        self.label_7.setStyleSheet("background:none;\n"
"border:none;\n"
"padding-left:10px;\n"
"color: rgba(255, 255, 255, 140);")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.frame_driver_protection_2 = QtWidgets.QFrame(self.toggle_frame_left)
        self.frame_driver_protection_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_driver_protection_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_driver_protection_2.setObjectName("frame_driver_protection_2")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_driver_protection_2)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.chat_history = QtWidgets.QListWidget(self.frame_driver_protection_2)
        self.chat_history.setObjectName("chat_history")
        self.verticalLayout_10.addWidget(self.chat_history)
        self.verticalLayout_3.addWidget(self.frame_driver_protection_2)
        self.frame_settings = QtWidgets.QFrame(self.toggle_frame_left)
        self.frame_settings.setMinimumSize(QtCore.QSize(0, 60))
        self.frame_settings.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_settings.setStyleSheet("QFrame{\n"
"    border-radius: 0px;\n"
"    border-top: 1px solid rgba(255, 255, 255, 30);\n"
"}\n"
"QFrame:hover{\n"
"    background-color: rgb(55, 62, 76);\n"
"    border:2px solid rgba(0, 159, 238, 140);\n"
"    border-radius:0px;\n"
"    border-bottom-left-radius:10px;\n"
"}")
        self.frame_settings.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_settings.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_settings.setObjectName("frame_settings")
        self.button_settings = QtWidgets.QPushButton(self.frame_settings)
        self.button_settings.setGeometry(QtCore.QRect(-2, 0, 221, 60))
        self.button_settings.setMinimumSize(QtCore.QSize(0, 60))
        self.button_settings.setMaximumSize(QtCore.QSize(250, 250))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(10)
        self.button_settings.setFont(font)
        self.button_settings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_settings.setStyleSheet("background:none;\n"
"border:none;\n"
"color: rgba(255, 255, 255, 180);")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("../Reqs/settings-50 copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.button_settings.setIcon(icon6)
        self.button_settings.setIconSize(QtCore.QSize(35, 35))
        self.button_settings.setObjectName("button_settings")
        self.verticalLayout_3.addWidget(self.frame_settings)
        self.horizontalLayout_4.addWidget(self.toggle_frame_left)
        self.content_page_frame = QtWidgets.QFrame(self.Content)
        self.content_page_frame.setStyleSheet("background-color:#2C313C;\n"
"border-radius:0px;\n"
"border-bottom-right-radius:10px;\n"
"")
        self.content_page_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_page_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_page_frame.setObjectName("content_page_frame")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.content_page_frame)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.stackedWidget = QtWidgets.QStackedWidget(self.content_page_frame)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.new_chat_page = QtWidgets.QWidget()
        self.new_chat_page.setObjectName("new_chat_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.new_chat_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.frame_8 = QtWidgets.QFrame(self.new_chat_page)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_11 = QtWidgets.QFrame(self.frame_8)
        self.frame_11.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_7.addWidget(self.frame_11)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_9.setMaximumSize(QtCore.QSize(600, 16777215))
        font = QtGui.QFont()
        font.setFamily("MingLiU_HKSCS-ExtB")
        self.frame_9.setFont(font)
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_9)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_12 = QtWidgets.QFrame(self.frame_9)
        self.frame_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label = QtWidgets.QLabel(self.frame_12)
        self.label.setStyleSheet("background:none;\n"
"border:none;")
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/san76/.designer/backup/Reqs/protected.png"))
        self.label.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_8.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_9)
        self.frame_13.setMinimumSize(QtCore.QSize(0, 400))
        self.frame_13.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.labelProtection = QtWidgets.QLabel(self.frame_13)
        self.labelProtection.setGeometry(QtCore.QRect(170, 60, 382, 54))
        self.labelProtection.setMaximumSize(QtCore.QSize(16777215, 80))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(30)
        self.labelProtection.setFont(font)
        self.labelProtection.setStyleSheet("background:none;\n"
"border:none;\n"
"color:rgba(255, 255, 255, 180);")
        self.labelProtection.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelProtection.setObjectName("labelProtection")
        self.searchButton = StickyButton(self.frame_13)
        self.searchButton.setGeometry(QtCore.QRect(642, 141, 45, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton.sizePolicy().hasHeightForWidth())
        self.searchButton.setSizePolicy(sizePolicy)
        self.searchButton.setMinimumSize(QtCore.QSize(45, 45))
        self.searchButton.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Medium")
        font.setPointSize(10)
        self.searchButton.setFont(font)
        self.searchButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton.setStyleSheet("QPushButton{\n"
"    background:none;\n"
"    border:none;\n"
"    color:rgba(255, 255, 255, 180);\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-radius: 21px ;\n"
"    margin-top:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(45, 48, 58);\n"
"}")
        self.searchButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("../Reqs/search.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.searchButton.setIcon(icon7)
        self.searchButton.setIconSize(QtCore.QSize(27, 27))
        self.searchButton.setObjectName("searchButton")
        self.addButton = StickyButton(self.frame_13)
        self.addButton.setGeometry(QtCore.QRect(12, 140, 51, 45))
        self.addButton.setMinimumSize(QtCore.QSize(0, 45))
        self.addButton.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Medium")
        font.setPointSize(10)
        self.addButton.setFont(font)
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setStyleSheet("QPushButton{\n"
"    background:none;\n"
"    border:none;\n"
"    color:rgba(255, 255, 255, 180);\n"
"    border-radius: 21px ;\n"
"    margin-top:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(45, 48, 58);\n"
"}")
        self.addButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("../Reqs/add_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.addButton.setIcon(icon8)
        self.addButton.setIconSize(QtCore.QSize(22, 22))
        self.addButton.setObjectName("addButton")
        self.text_prompt = AutoGrowTextEdit(self.frame_13)
        self.text_prompt.setEnabled(True)
        self.text_prompt.setGeometry(QtCore.QRect(10, 140, 681, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_prompt.sizePolicy().hasHeightForWidth())
        self.text_prompt.setSizePolicy(sizePolicy)
        self.text_prompt.setMinimumSize(QtCore.QSize(0, 50))
        self.text_prompt.setMaximumSize(QtCore.QSize(16777215, 50))
        self.text_prompt.setSizeIncrement(QtCore.QSize(0, 0))
        self.text_prompt.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.text_prompt.setFont(font)
        self.text_prompt.setStyleSheet("QTextEdit{\n"
"     border:2px solid rgb(41, 44, 53);\n"
"    border-radius:22px;\n"
"    background-color: rgb(41, 44, 53);\n"
"    color:rgba(255,     255, 255, 210);\n"
"    padding-left:20px;\n"
"    padding-top:10px;\n"
"    padding-right:15px;\n"
"    padding-bottom:45px;\n"
"}\n"
"\n"
"QTextEdit:hover{\n"
"    border:2px solid rgb(220, 0, 220);\n"
"}\n"
"\n"
"QTextEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.text_prompt.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_prompt.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_prompt.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.text_prompt.setObjectName("text_prompt")
        self.text_prompt.raise_()
        self.labelProtection.raise_()
        self.searchButton.raise_()
        self.addButton.raise_()
        self.verticalLayout_6.addWidget(self.frame_13)
        self.frame_14 = QtWidgets.QFrame(self.frame_9)
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_6.addWidget(self.frame_14)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.frame_10 = QtWidgets.QFrame(self.frame_8)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_10)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_21 = QtWidgets.QFrame(self.frame_10)
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_21.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.frame_21)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.frame_23 = QtWidgets.QFrame(self.frame_21)
        self.frame_23.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_23.setObjectName("frame_23")
        self.horizontalLayout_16.addWidget(self.frame_23)
        self.frame_24 = QtWidgets.QFrame(self.frame_21)
        self.frame_24.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_24.setMaximumSize(QtCore.QSize(120, 16777215))
        self.frame_24.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_24.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_24.setObjectName("frame_24")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.frame_24)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.login_button = QtWidgets.QPushButton(self.frame_24)
        self.login_button.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        self.login_button.setFont(font)
        self.login_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.login_button.setStyleSheet("QPushButton{\n"
"    color: rgba(255, 255, 255, 200);\n"
"    background-color: rgb(48, 53, 65);\n"
"    \n"
"    border-radius:10px;\n"
"}\n"
"QPushButton:hover{\n"
"    color:rgb(85, 170, 255);\n"
"    background-color:rgb(52, 57, 70)\n"
"}")
        self.login_button.setObjectName("login_button")
        self.horizontalLayout_17.addWidget(self.login_button)
        self.horizontalLayout_16.addWidget(self.frame_24)
        self.verticalLayout_11.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_10)
        self.frame_22.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_11.addWidget(self.frame_22)
        self.horizontalLayout_7.addWidget(self.frame_10)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.stackedWidget.addWidget(self.new_chat_page)
        self.settings_page = QtWidgets.QWidget()
        self.settings_page.setObjectName("settings_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.settings_page)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_48 = QtWidgets.QFrame(self.settings_page)
        self.frame_48.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_48.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_48.setObjectName("frame_48")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.frame_48)
        self.horizontalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_22.setSpacing(0)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.frame_49 = QtWidgets.QFrame(self.frame_48)
        self.frame_49.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_49.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame_49.setStyleSheet("background-color: rgb(43, 47, 58)")
        self.frame_49.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_49.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_49.setObjectName("frame_49")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_49)
        self.verticalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_27.setSpacing(10)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.frame_51 = QtWidgets.QFrame(self.frame_49)
        self.frame_51.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame_51.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_51.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_51.setObjectName("frame_51")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.frame_51)
        self.horizontalLayout_23.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_23.setSpacing(0)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_32 = QtWidgets.QLabel(self.frame_51)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setStyleSheet("color:rgba(255, 255, 255, 180);")
        self.label_32.setAlignment(QtCore.Qt.AlignCenter)
        self.label_32.setObjectName("label_32")
        self.horizontalLayout_23.addWidget(self.label_32)
        self.verticalLayout_27.addWidget(self.frame_51)
        self.frame_25 = QtWidgets.QFrame(self.frame_49)
        self.frame_25.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_25.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_25.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_25.setObjectName("frame_25")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.frame_25)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(0)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.acc_button = QtWidgets.QPushButton(self.frame_25)
        self.acc_button.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.acc_button.setFont(font)
        self.acc_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.acc_button.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.acc_button.setObjectName("acc_button")
        self.horizontalLayout_18.addWidget(self.acc_button)
        self.verticalLayout_27.addWidget(self.frame_25)
        self.frame_56 = QtWidgets.QFrame(self.frame_49)
        self.frame_56.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_56.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_56.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_56.setObjectName("frame_56")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.frame_56)
        self.horizontalLayout_24.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_24.setSpacing(0)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.buttonUI = QtWidgets.QPushButton(self.frame_56)
        self.buttonUI.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.buttonUI.setFont(font)
        self.buttonUI.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonUI.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.buttonUI.setObjectName("buttonUI")
        self.horizontalLayout_24.addWidget(self.buttonUI)
        self.verticalLayout_27.addWidget(self.frame_56)
        self.frame_52 = QtWidgets.QFrame(self.frame_49)
        self.frame_52.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_52.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_52.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_52.setObjectName("frame_52")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.frame_52)
        self.horizontalLayout_25.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_25.setSpacing(0)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.buttonNotification = QtWidgets.QPushButton(self.frame_52)
        self.buttonNotification.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.buttonNotification.setFont(font)
        self.buttonNotification.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonNotification.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.buttonNotification.setObjectName("buttonNotification")
        self.horizontalLayout_25.addWidget(self.buttonNotification)
        self.verticalLayout_27.addWidget(self.frame_52)
        self.frame_53 = QtWidgets.QFrame(self.frame_49)
        self.frame_53.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_53.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_53.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_53.setObjectName("frame_53")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.frame_53)
        self.horizontalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_26.setSpacing(0)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.buttonUpdate = QtWidgets.QPushButton(self.frame_53)
        self.buttonUpdate.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.buttonUpdate.setFont(font)
        self.buttonUpdate.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonUpdate.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.buttonUpdate.setObjectName("buttonUpdate")
        self.horizontalLayout_26.addWidget(self.buttonUpdate)
        self.verticalLayout_27.addWidget(self.frame_53)
        self.button_preferences = QtWidgets.QPushButton(self.frame_49)
        self.button_preferences.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.button_preferences.setFont(font)
        self.button_preferences.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_preferences.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.button_preferences.setObjectName("button_preferences")
        self.verticalLayout_27.addWidget(self.button_preferences)
        self.frame_54 = QtWidgets.QFrame(self.frame_49)
        self.frame_54.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_54.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_54.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_54.setObjectName("frame_54")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.frame_54)
        self.horizontalLayout_27.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_27.setSpacing(0)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.buttonAbout = QtWidgets.QPushButton(self.frame_54)
        self.buttonAbout.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.buttonAbout.setFont(font)
        self.buttonAbout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.buttonAbout.setStyleSheet("QPushButton{\n"
"    border-radius:5px;\n"
"    color:rgb(180, 180, 180);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color:rgb(59, 66, 81);\n"
"    border:2px solid rgb(212, 58, 212);\n"
"    border-radius:5px;\n"
"}")
        self.buttonAbout.setObjectName("buttonAbout")
        self.horizontalLayout_27.addWidget(self.buttonAbout)
        self.verticalLayout_27.addWidget(self.frame_54)
        self.frame_57 = QtWidgets.QFrame(self.frame_49)
        self.frame_57.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_57.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_57.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_57.setObjectName("frame_57")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.frame_57)
        self.horizontalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_28.setSpacing(0)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.verticalLayout_27.addWidget(self.frame_57)
        self.frame_55 = QtWidgets.QFrame(self.frame_49)
        self.frame_55.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_55.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_55.setObjectName("frame_55")
        self.verticalLayout_27.addWidget(self.frame_55)
        self.horizontalLayout_22.addWidget(self.frame_49)
        self.frame_50 = QtWidgets.QFrame(self.frame_48)
        self.frame_50.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_50.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_50.setObjectName("frame_50")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_50)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.setting_pages = QtWidgets.QStackedWidget(self.frame_50)
        self.setting_pages.setObjectName("setting_pages")
        self.preference_page = QtWidgets.QWidget()
        self.preference_page.setObjectName("preference_page")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.preference_page)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.frame_5 = QtWidgets.QFrame(self.preference_page)
        self.frame_5.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_9.addWidget(self.frame_5)
        self.frame_3 = QtWidgets.QFrame(self.preference_page)
        self.frame_3.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_9.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.frame_6 = QtWidgets.QFrame(self.frame_3)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_2 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_10.addWidget(self.label_2)
        self.verticalLayout_9.addWidget(self.frame_6)
        self.frame_15 = QtWidgets.QFrame(self.frame_3)
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_15.setStyleSheet("#frame_15{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_11.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_3 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setWhatsThis("")
        self.label_3.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;\n"
"padding-top:15px;")
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_11.addWidget(self.label_3)
        self.learning_type = QtWidgets.QComboBox(self.frame_15)
        self.learning_type.setMinimumSize(QtCore.QSize(0, 30))
        self.learning_type.setMaximumSize(QtCore.QSize(130, 16777215))
        self.learning_type.setStyleSheet("QComboBox {\n"
"    background:transparent ;\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 6px;\n"
"    padding: 6px 10px;\n"
"    padding-right: 30px; /* space for arrow */\n"
"    font-size: 14px;\n"
"    color:rgb(190, 190, 190);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #90caf9;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3a7bd5;\n"
"}\n"
"\n"
"/* Dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(52, 58, 71);\n"
"    color:rgb(190, 190, 190);\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    selection-background-color:rgb(56, 63, 77);\n"
"    selection-color: rgb(200, 200, 200);\n"
"    padding: 5px;\n"
"    outline: 0;\n"
"    min-height: 80px;\n"
"}\n"
"\n"
"/* Selected item */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 0px;\n"
"    font-size: 14px;\n"
"    min-height:40px;\n"
"    \n"
"}\n"
"\n"
"/* Hover item */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.learning_type.setObjectName("learning_type")
        self.learning_type.addItem("")
        self.learning_type.addItem("")
        self.learning_type.addItem("")
        self.horizontalLayout_11.addWidget(self.learning_type)
        self.verticalLayout_9.addWidget(self.frame_15)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_7.setStyleSheet("#frame_7{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_12.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;\n"
"padding-top:15px;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_12.addWidget(self.label_4)
        self.difficulty_type = QtWidgets.QComboBox(self.frame_7)
        self.difficulty_type.setMinimumSize(QtCore.QSize(0, 30))
        self.difficulty_type.setMaximumSize(QtCore.QSize(130, 16777215))
        self.difficulty_type.setStyleSheet("QComboBox {\n"
"    background:transparent ;\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 6px;\n"
"    padding: 6px 10px;\n"
"    padding-right: 30px; /* space for arrow */\n"
"    font-size: 14px;\n"
"    color:rgb(190, 190, 190);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #90caf9;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3a7bd5;\n"
"}\n"
"\n"
"/* Dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(52, 58, 71);\n"
"    color:rgb(190, 190, 190);\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    selection-background-color:rgb(56, 63, 77);\n"
"    selection-color: rgb(200, 200, 200);\n"
"    padding: 5px;\n"
"    outline: 0;\n"
"    min-height: 80px;\n"
"}\n"
"\n"
"/* Selected item */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 0px;\n"
"    font-size: 14px;\n"
"    min-height:40px;\n"
"    \n"
"}\n"
"\n"
"/* Hover item */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.difficulty_type.setObjectName("difficulty_type")
        self.difficulty_type.addItem("")
        self.difficulty_type.addItem("")
        self.difficulty_type.addItem("")
        self.horizontalLayout_12.addWidget(self.difficulty_type)
        self.verticalLayout_9.addWidget(self.frame_7)
        self.frame_16 = QtWidgets.QFrame(self.frame_3)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_16.setStyleSheet("#frame_16{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_15.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_15.setSpacing(10)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_5 = QtWidgets.QLabel(self.frame_16)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;\n"
"padding-top:15px;")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_15.addWidget(self.label_5)
        self.spinHour = QtWidgets.QSpinBox(self.frame_16)
        self.spinHour.setEnabled(True)
        self.spinHour.setMaximumSize(QtCore.QSize(61, 31))
        self.spinHour.setStyleSheet("QSpinBox {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(139, 139, 139);\n"
"    border-radius: 6px;\n"
"    padding: 4px 15px 4px 8px;  /* space for arrows */\n"
"    font-size: 14px;\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border: 1px solid #90caf9;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #42a5f5;\n"
"}\n"
"\n"
"/* Up & Down buttons */\n"
"QSpinBox::up-button,\n"
"QSpinBox::down-button {\n"
"    width: 18px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(56, 63, 77);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrows */\n"
"QSpinBox::up-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-bottom: 6px solid #546e7a;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-top: 6px solid #546e7a;\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QSpinBox:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #9e9e9e;\n"
"    border: 1px solid #e0e0e0;\n"
"}\n"
"")
        self.spinHour.setObjectName("spinHour")
        self.horizontalLayout_15.addWidget(self.spinHour)
        self.spinMinute = QtWidgets.QSpinBox(self.frame_16)
        self.spinMinute.setMaximumSize(QtCore.QSize(61, 31))
        self.spinMinute.setStyleSheet("QSpinBox {\n"
"    background-color: transparent;\n"
"    border: 1px solid rgb(139, 139, 139);\n"
"    border-radius: 6px;\n"
"    padding: 4px 15px 4px 8px;  /* space for arrows */\n"
"    font-size: 14px;\n"
"    color: rgb(200, 200, 200);\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border: 1px solid #90caf9;\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border: 1px solid #42a5f5;\n"
"}\n"
"\n"
"/* Up & Down buttons */\n"
"QSpinBox::up-button,\n"
"QSpinBox::down-button {\n"
"    width: 18px;\n"
"    background-color: transparent;\n"
"    border: none;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover,\n"
"QSpinBox::down-button:hover {\n"
"    background-color: rgb(56, 63, 77);\n"
"    border-radius: 4px;\n"
"}\n"
"\n"
"/* Arrows */\n"
"QSpinBox::up-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-bottom: 6px solid #546e7a;\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: none;\n"
"    width: 0;\n"
"    height: 0;\n"
"    border-left: 3px solid transparent;\n"
"    border-right: 3px solid transparent;\n"
"    border-top: 6px solid #546e7a;\n"
"}\n"
"\n"
"/* Disabled state */\n"
"QSpinBox:disabled {\n"
"    background-color: #f5f5f5;\n"
"    color: #9e9e9e;\n"
"    border: 1px solid #e0e0e0;\n"
"}\n"
"")
        self.spinMinute.setObjectName("spinMinute")
        self.horizontalLayout_15.addWidget(self.spinMinute)
        self.verticalLayout_9.addWidget(self.frame_16)
        self.frame_17 = QtWidgets.QFrame(self.frame_3)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_17.setStyleSheet("#frame_17{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_17)
        self.horizontalLayout_14.setContentsMargins(20, 0, 20, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(self.frame_17)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;\n"
"padding-top:15px;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.preferred_output = QtWidgets.QComboBox(self.frame_17)
        self.preferred_output.setMinimumSize(QtCore.QSize(0, 30))
        self.preferred_output.setMaximumSize(QtCore.QSize(130, 16777215))
        self.preferred_output.setStyleSheet("QComboBox {\n"
"    background:transparent ;\n"
"    border: 1px solid rgb(130, 130, 130);\n"
"    border-radius: 6px;\n"
"    padding: 6px 10px;\n"
"    padding-right: 30px; /* space for arrow */\n"
"    font-size: 14px;\n"
"    color:rgb(190, 190, 190);\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border: 1px solid #5a9bd5;\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border: 1px solid #3a7bd5;\n"
"}\n"
"\n"
"/* Dropdown list */\n"
"QComboBox QAbstractItemView {\n"
"    background-color: rgb(52, 58, 71);\n"
"    color:rgb(190, 190, 190);\n"
"    border: 1px solid #c4c4c4;\n"
"    border-radius: 5px;\n"
"    selection-background-color:rgb(56, 63, 77);\n"
"    selection-color: rgb(200, 200, 200);\n"
"    padding: 5px;\n"
"    outline: 0;\n"
"    min-height: 80px;\n"
"}\n"
"\n"
"/* Selected item */\n"
"QComboBox QAbstractItemView::item {\n"
"    padding: 0px;\n"
"    font-size: 14px;\n"
"    min-height:40px;\n"
"    \n"
"}\n"
"\n"
"/* Hover item */\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: #fff;\n"
"}\n"
"\n"
"\n"
"")
        self.preferred_output.setObjectName("preferred_output")
        self.preferred_output.addItem("")
        self.preferred_output.addItem("")
        self.preferred_output.addItem("")
        self.preferred_output.addItem("")
        self.horizontalLayout_14.addWidget(self.preferred_output)
        self.verticalLayout_9.addWidget(self.frame_17)
        self.frame_19 = QtWidgets.QFrame(self.frame_3)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 80))
        self.frame_19.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_19)
        self.horizontalLayout_13.setContentsMargins(-1, 20, -1, 0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.frame_20 = QtWidgets.QFrame(self.frame_19)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_20.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.horizontalLayout_13.addWidget(self.frame_20)
        self.button_save = QtWidgets.QPushButton(self.frame_19)
        self.button_save.setMinimumSize(QtCore.QSize(100, 32))
        self.button_save.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        self.button_save.setFont(font)
        self.button_save.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_save.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_save.setStyleSheet("QPushButton{\n"
"    color:  rgb(180, 180, 180);\n"
"    border: 2px solid #5a9bd5;\n"
"    border-radius : 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(56, 63, 77);\n"
"    border: 2px solid rgb(170, 0, 255);\n"
"}")
        self.button_save.setObjectName("button_save")
        self.horizontalLayout_13.addWidget(self.button_save)
        self.verticalLayout_9.addWidget(self.frame_19)
        self.frame_18 = QtWidgets.QFrame(self.frame_3)
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_9.addWidget(self.frame_18)
        self.horizontalLayout_9.addWidget(self.frame_3)
        self.frame_4 = QtWidgets.QFrame(self.preference_page)
        self.frame_4.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.horizontalLayout_9.addWidget(self.frame_4)
        self.setting_pages.addWidget(self.preference_page)
        self.account_page = QtWidgets.QWidget()
        self.account_page.setObjectName("account_page")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.account_page)
        self.horizontalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.frame_27 = QtWidgets.QFrame(self.account_page)
        self.frame_27.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_27.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.horizontalLayout_19.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.account_page)
        self.frame_28.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_28.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_12.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.frame_29 = QtWidgets.QFrame(self.frame_28)
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_29.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.frame_29)
        self.horizontalLayout_20.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.account_label = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        self.account_label.setFont(font)
        self.account_label.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.account_label.setObjectName("account_label")
        self.horizontalLayout_20.addWidget(self.account_label)
        self.logged_in_label = QtWidgets.QLabel(self.frame_29)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.logged_in_label.setFont(font)
        self.logged_in_label.setStyleSheet("color: rgba(255, 0, 0, 200);")
        self.logged_in_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.logged_in_label.setObjectName("logged_in_label")
        self.horizontalLayout_20.addWidget(self.logged_in_label)
        self.verticalLayout_12.addWidget(self.frame_29)
        self.frame_30 = QtWidgets.QFrame(self.frame_28)
        self.frame_30.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.frame_32 = QtWidgets.QFrame(self.frame_30)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_32.setStyleSheet("#frame_32{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.frame_32.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.username_label = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.username_label.setFont(font)
        self.username_label.setWhatsThis("")
        self.username_label.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.username_label.setObjectName("username_label")
        self.verticalLayout_14.addWidget(self.username_label)
        self.email_label = QtWidgets.QLabel(self.frame_32)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.email_label.setFont(font)
        self.email_label.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.email_label.setObjectName("email_label")
        self.verticalLayout_14.addWidget(self.email_label)
        self.verticalLayout_13.addWidget(self.frame_32)
        self.frame_33 = QtWidgets.QFrame(self.frame_30)
        self.frame_33.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_33.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_33.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_33.setObjectName("frame_33")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.frame_33)
        self.horizontalLayout_21.setContentsMargins(-1, -1, 30, -1)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.frame_34 = QtWidgets.QFrame(self.frame_33)
        self.frame_34.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_34.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_34.setObjectName("frame_34")
        self.horizontalLayout_21.addWidget(self.frame_34)
        self.button_logout = QtWidgets.QPushButton(self.frame_33)
        self.button_logout.setMinimumSize(QtCore.QSize(100, 32))
        self.button_logout.setMaximumSize(QtCore.QSize(120, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        self.button_logout.setFont(font)
        self.button_logout.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_logout.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_logout.setStyleSheet("QPushButton{\n"
"    color:  rgb(180, 180, 180);\n"
"    border: 1px solid #5a9bd5;\n"
"    border-radius : 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(56, 63, 77);\n"
"    border: 2px solid rgb(170, 0, 255);\n"
"}")
        self.button_logout.setObjectName("button_logout")
        self.horizontalLayout_21.addWidget(self.button_logout)
        self.verticalLayout_13.addWidget(self.frame_33)
        self.frame_31 = QtWidgets.QFrame(self.frame_30)
        self.frame_31.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_13.addWidget(self.frame_31)
        self.verticalLayout_12.addWidget(self.frame_30)
        self.horizontalLayout_19.addWidget(self.frame_28)
        self.frame_26 = QtWidgets.QFrame(self.account_page)
        self.frame_26.setMaximumSize(QtCore.QSize(350, 16777215))
        self.frame_26.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.horizontalLayout_19.addWidget(self.frame_26)
        self.setting_pages.addWidget(self.account_page)
        self.about_page = QtWidgets.QWidget()
        self.about_page.setObjectName("about_page")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.about_page)
        self.horizontalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_29.setSpacing(0)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.frame_35 = QtWidgets.QFrame(self.about_page)
        self.frame_35.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout(self.frame_35)
        self.horizontalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_32.setSpacing(0)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_36 = QtWidgets.QFrame(self.frame_35)
        self.frame_36.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.horizontalLayout_32.addWidget(self.frame_36)
        self.frame_38 = QtWidgets.QFrame(self.frame_35)
        self.frame_38.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_38.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_15.setContentsMargins(0, 20, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.frame_39 = QtWidgets.QFrame(self.frame_38)
        self.frame_39.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_39.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.frame_39)
        self.horizontalLayout_30.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.account_label_2 = QtWidgets.QLabel(self.frame_39)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(13)
        self.account_label_2.setFont(font)
        self.account_label_2.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.account_label_2.setObjectName("account_label_2")
        self.horizontalLayout_30.addWidget(self.account_label_2)
        self.verticalLayout_15.addWidget(self.frame_39)
        self.frame_40 = QtWidgets.QFrame(self.frame_38)
        self.frame_40.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_41.setStyleSheet("#frame_41{\n"
"    background-color: rgb(52, 58, 71);\n"
"    border-radius:0px;\n"
"    border-top-left-radius:10px;\n"
"    border-top-right-radius:10px;\n"
"    border-bottom-left-radius:10px;\n"
"    border-bottom-right-radius:10px;\n"
"}")
        self.frame_41.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.label_11 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setWhatsThis("")
        self.label_11.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.label_11.setObjectName("label_11")
        self.verticalLayout_17.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color:rgb(180, 180, 180);\n"
"background:transparent;")
        self.label_12.setObjectName("label_12")
        self.verticalLayout_17.addWidget(self.label_12)
        self.verticalLayout_16.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_40)
        self.frame_42.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_42.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.horizontalLayout_31 = QtWidgets.QHBoxLayout(self.frame_42)
        self.horizontalLayout_31.setContentsMargins(-1, -1, 40, -1)
        self.horizontalLayout_31.setObjectName("horizontalLayout_31")
        self.frame_43 = QtWidgets.QFrame(self.frame_42)
        self.frame_43.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_43.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_43.setObjectName("frame_43")
        self.horizontalLayout_31.addWidget(self.frame_43)
        self.button_check_update = QtWidgets.QPushButton(self.frame_42)
        self.button_check_update.setMinimumSize(QtCore.QSize(100, 32))
        self.button_check_update.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Roboto Medium")
        font.setPointSize(9)
        self.button_check_update.setFont(font)
        self.button_check_update.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.button_check_update.setFocusPolicy(QtCore.Qt.NoFocus)
        self.button_check_update.setStyleSheet("QPushButton{\n"
"    color:  rgb(180, 180, 180);\n"
"    border: 1px solid #5a9bd5;\n"
"    border-radius : 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(56, 63, 77);\n"
"    border: 2px solid rgb(170, 0, 255);\n"
"}")
        self.button_check_update.setObjectName("button_check_update")
        self.horizontalLayout_31.addWidget(self.button_check_update)
        self.verticalLayout_16.addWidget(self.frame_42)
        self.frame_44 = QtWidgets.QFrame(self.frame_40)
        self.frame_44.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_44.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_44.setObjectName("frame_44")
        self.verticalLayout_16.addWidget(self.frame_44)
        self.verticalLayout_15.addWidget(self.frame_40)
        self.horizontalLayout_32.addWidget(self.frame_38)
        self.frame_37 = QtWidgets.QFrame(self.frame_35)
        self.frame_37.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.horizontalLayout_32.addWidget(self.frame_37)
        self.horizontalLayout_29.addWidget(self.frame_35)
        self.setting_pages.addWidget(self.about_page)
        self.verticalLayout_8.addWidget(self.setting_pages)
        self.horizontalLayout_22.addWidget(self.frame_50)
        self.verticalLayout_4.addWidget(self.frame_48)
        self.stackedWidget.addWidget(self.settings_page)
        self.conversation_page = QtWidgets.QWidget()
        self.conversation_page.setObjectName("conversation_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.conversation_page)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.frame = QtWidgets.QFrame(self.conversation_page)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_33.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_33.setSpacing(0)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.frame_46 = QtWidgets.QFrame(self.frame)
        self.frame_46.setMinimumSize(QtCore.QSize(280, 0))
        self.frame_46.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_46.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_46.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_46.setObjectName("frame_46")
        self.horizontalLayout_33.addWidget(self.frame_46)
        self.frame_45 = QtWidgets.QFrame(self.frame)
        self.frame_45.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_45.setMaximumSize(QtCore.QSize(1100, 16777215))
        self.frame_45.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_45.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_45.setObjectName("frame_45")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_45)
        self.verticalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.frame_58 = QtWidgets.QFrame(self.frame_45)
        self.frame_58.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_58.setStyleSheet("background-color: rgb(50, 56, 68);")
        self.frame_58.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_58.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_58.setObjectName("frame_58")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_58)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.chat_layout = QtWidgets.QVBoxLayout()
        self.chat_layout.setObjectName("chat_layout")
        self.verticalLayout_20.addLayout(self.chat_layout)
        self.verticalLayout_18.addWidget(self.frame_58)
        self.frame_2 = QtWidgets.QFrame(self.frame_45)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 150))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_34 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_34.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_34.setSpacing(0)
        self.horizontalLayout_34.setObjectName("horizontalLayout_34")
        self.frame_59 = QtWidgets.QFrame(self.frame_2)
        self.frame_59.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_59.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_59.setObjectName("frame_59")
        self.horizontalLayout_34.addWidget(self.frame_59)
        self.frame_60 = QtWidgets.QFrame(self.frame_2)
        self.frame_60.setMinimumSize(QtCore.QSize(700, 0))
        self.frame_60.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_60.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_60.setObjectName("frame_60")
        self.addButton_2 = StickyButton(self.frame_60)
        self.addButton_2.setGeometry(QtCore.QRect(10, 50, 51, 45))
        self.addButton_2.setMinimumSize(QtCore.QSize(0, 45))
        self.addButton_2.setMaximumSize(QtCore.QSize(160, 16777215))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Medium")
        font.setPointSize(10)
        self.addButton_2.setFont(font)
        self.addButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton_2.setStyleSheet("QPushButton{\n"
"    background:none;\n"
"    border:none;\n"
"    color:rgba(255, 255, 255, 180);\n"
"    border-radius: 21px ;\n"
"    margin-top:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(45, 48, 58);\n"
"}")
        self.addButton_2.setText("")
        self.addButton_2.setIcon(icon8)
        self.addButton_2.setIconSize(QtCore.QSize(22, 22))
        self.addButton_2.setObjectName("addButton_2")
        self.text_prompt_2 = AutoGrowTextEdit(self.frame_60)
        self.text_prompt_2.setEnabled(True)
        self.text_prompt_2.setGeometry(QtCore.QRect(10, 50, 681, 50))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.text_prompt_2.sizePolicy().hasHeightForWidth())
        self.text_prompt_2.setSizePolicy(sizePolicy)
        self.text_prompt_2.setMinimumSize(QtCore.QSize(0, 50))
        self.text_prompt_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.text_prompt_2.setSizeIncrement(QtCore.QSize(0, 0))
        self.text_prompt_2.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Roboto")
        font.setPointSize(10)
        self.text_prompt_2.setFont(font)
        self.text_prompt_2.setStyleSheet("QTextEdit{\n"
"     border:2px solid rgb(41, 44, 53);\n"
"    border-radius:22px;\n"
"    background-color: rgb(41, 44, 53);\n"
"    color:rgba(255,     255, 255, 210);\n"
"    padding-left:20px;\n"
"    padding-top:10px;\n"
"    padding-right:15px;\n"
"    padding-bottom:45px;\n"
"}\n"
"\n"
"QTextEdit:hover{\n"
"    border:2px solid rgb(220, 0, 220);\n"
"}\n"
"\n"
"QTextEdit:focus{\n"
"    border:2px solid rgb(85,170,255);\n"
"}")
        self.text_prompt_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.text_prompt_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.text_prompt_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.text_prompt_2.setObjectName("text_prompt_2")
        self.searchButton_2 = StickyButton(self.frame_60)
        self.searchButton_2.setGeometry(QtCore.QRect(640, 50, 45, 45))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.searchButton_2.sizePolicy().hasHeightForWidth())
        self.searchButton_2.setSizePolicy(sizePolicy)
        self.searchButton_2.setMinimumSize(QtCore.QSize(45, 45))
        self.searchButton_2.setMaximumSize(QtCore.QSize(45, 45))
        font = QtGui.QFont()
        font.setFamily("Noto Sans Medium")
        font.setPointSize(10)
        self.searchButton_2.setFont(font)
        self.searchButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.searchButton_2.setStyleSheet("QPushButton{\n"
"    background:none;\n"
"    border:none;\n"
"    color:rgba(255, 255, 255, 180);\n"
"    background-color: rgb(41, 44, 53);\n"
"    border-radius: 21px ;\n"
"    margin-top:3px;\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(45, 48, 58);\n"
"}")
        self.searchButton_2.setText("")
        self.searchButton_2.setIcon(icon7)
        self.searchButton_2.setIconSize(QtCore.QSize(27, 27))
        self.searchButton_2.setObjectName("searchButton_2")
        self.text_prompt_2.raise_()
        self.addButton_2.raise_()
        self.searchButton_2.raise_()
        self.horizontalLayout_34.addWidget(self.frame_60)
        self.frame_61 = QtWidgets.QFrame(self.frame_2)
        self.frame_61.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_61.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_61.setObjectName("frame_61")
        self.horizontalLayout_34.addWidget(self.frame_61)
        self.verticalLayout_18.addWidget(self.frame_2)
        self.horizontalLayout_33.addWidget(self.frame_45)
        self.frame_47 = QtWidgets.QFrame(self.frame)
        self.frame_47.setMinimumSize(QtCore.QSize(280, 0))
        self.frame_47.setMaximumSize(QtCore.QSize(400, 16777215))
        self.frame_47.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_47.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_47.setObjectName("frame_47")
        self.horizontalLayout_33.addWidget(self.frame_47)
        self.verticalLayout_7.addWidget(self.frame)
        self.stackedWidget.addWidget(self.conversation_page)
        self.horizontalLayout_6.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.content_page_frame)
        self.verticalLayout_2.addWidget(self.Content)
        self.verticalLayout.addWidget(self.drop_shadow_frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status_bar.setText(_translate("MainWindow", "  AI Personalized Learning App"))
        self.button_new_chat.setText(_translate("MainWindow", "     New Chat           "))
        self.label_7.setText(_translate("MainWindow", "Recent chats"))
        self.button_settings.setText(_translate("MainWindow", "      Settings        "))
        self.labelProtection.setText(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:30pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'ui-sans-serif\',\'-apple-system\',\'system-ui\',\'Segoe UI\',\'Helvetica\',\'Apple Color Emoji\',\'Arial\',\'sans-serif\',\'Segoe UI Emoji\',\'Segoe UI Symbol\'; font-size:24pt;\">What can I help with?</span></p></body></html>"))
        self.text_prompt.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.text_prompt.setPlaceholderText(_translate("MainWindow", "Ask Anything"))
        self.login_button.setToolTip(_translate("MainWindow", "Not logged in!"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.label_32.setText(_translate("MainWindow", "Settings"))
        self.acc_button.setText(_translate("MainWindow", "Account"))
        self.buttonUI.setText(_translate("MainWindow", "User Interface"))
        self.buttonNotification.setText(_translate("MainWindow", "Notifications"))
        self.buttonUpdate.setText(_translate("MainWindow", "Update"))
        self.button_preferences.setText(_translate("MainWindow", "Preferences"))
        self.buttonAbout.setText(_translate("MainWindow", "About"))
        self.label_2.setText(_translate("MainWindow", "Preferences"))
        self.label_3.setText(_translate("MainWindow", "<span style=\"font-size:18px;\">Learning style</span><br>\n"
"<span style=\"font-size:16px;color:rgb(150, 150, 150)\">Choose your learning style as visual/text/quiz</span><br>\n"
""))
        self.learning_type.setItemText(0, _translate("MainWindow", "Text"))
        self.learning_type.setItemText(1, _translate("MainWindow", "Visual"))
        self.learning_type.setItemText(2, _translate("MainWindow", "Quiz"))
        self.label_4.setText(_translate("MainWindow", "<span style=\"font-size:18px;\">Diffiulty</span><br>\n"
"<span style=\"font-size:16px;color:rgb(150, 150, 150)\">Select your difficulty level as easy/medium/high</span><br>\n"
""))
        self.difficulty_type.setItemText(0, _translate("MainWindow", "Easy"))
        self.difficulty_type.setItemText(1, _translate("MainWindow", "Medium"))
        self.difficulty_type.setItemText(2, _translate("MainWindow", "Hard"))
        self.label_5.setText(_translate("MainWindow", "<span style=\"font-size:18px;\">Daily goal H:M</span><br>\n"
"<span style=\"font-size:16px;color:rgb(150, 150, 150)\">Set your daily goal example 1 hour, 30 min etc</span><br>\n"
""))
        self.label_6.setText(_translate("MainWindow", "<span style=\"font-size:18px;\">Preferred output</span><br>\n"
"<span style=\"font-size:16px;color:rgb(150, 150, 150)\">Set your preffered output as summary, MCQs or flashcards</span><br>\n"
""))
        self.preferred_output.setItemText(0, _translate("MainWindow", "Search"))
        self.preferred_output.setItemText(1, _translate("MainWindow", "Summary"))
        self.preferred_output.setItemText(2, _translate("MainWindow", "MCQs"))
        self.preferred_output.setItemText(3, _translate("MainWindow", "Flashcard"))
        self.button_save.setText(_translate("MainWindow", "Save"))
        self.account_label.setText(_translate("MainWindow", "Account"))
        self.logged_in_label.setText(_translate("MainWindow", " Not Logged In"))
        self.username_label.setText(_translate("MainWindow", "Username: "))
        self.email_label.setText(_translate("MainWindow", "Email: "))
        self.button_logout.setText(_translate("MainWindow", "Log In"))
        self.account_label_2.setText(_translate("MainWindow", "About"))
        self.label_11.setText(_translate("MainWindow", "AI Personalized Learning App"))
        self.label_12.setText(_translate("MainWindow", "version: 1.0"))
        self.button_check_update.setText(_translate("MainWindow", "Check for Update"))
        self.text_prompt_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Roboto\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:7.8pt;\"><br /></p></body></html>"))
        self.text_prompt_2.setPlaceholderText(_translate("MainWindow", "Ask Anything"))
from ui_controllers.auto_grow_text_edit import AutoGrowTextEdit
from ui_controllers.sticky_search_button import StickyButton


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
